definitions:

  steps:

    - step: &test
        name: "Test"
        image: python:3.7.4-slim
        caches:
          - pip
        script:
          - source ./devops/pipelines/test.sh

    - step: &propagate
        name: "Propagate changes"
        script:
          - source ./devops/pipelines/propagate.sh

    - step: &generate
        name: "Generate components"
        image: python:3.7.4
        script:
          - source ./devops/pipelines/generate.sh
        artifacts:
          - src/**

  stepsWithVariables:
    - variables: &generate-yml
        - name: GENERATE_YML_BASE64


# Pipelines
pipelines:

  # Perform propagate step on each touched branch
  branches:

    archetype/*:
      - step: *propagate
    develop/**:
      - step: *propagate
    dev:
      - step: *test
      - step: *propagate
    master:
      - step: *propagate

  # Manual pipelines
  custom:

    # Generate components
    generate-components:
      - variables: *generate-yml
      - step: *generate

